spring.application.name=springai
spring.config.import=optional:file:.env[.properties]
spring.ai.google.genai.api-key=${GOOGLE_GEN_AI_API}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
server.port=${PORT:8080}